### ISSUE TITLE
Can't install python requirements in Windows

### ISSUE THREAD

**Issue by marcurdy** [mkorman90/VolatilityBot#1]
Is there a non-Visual Studios method of meeting the project's dependency requirements?  distorm3 and yara-python.   

My Linux instance is a VM, and running a VM in my VM is less than optimal for testing in my situation..

**Comment by Beercow** [comment]
Google is your friend. 

Distorm3 binaries for Windows are here:
https://github.com/gdabah/distorm/releases

Yara-python binaries for Windows are here:
https://drive.google.com/drive/mobile/folders/0BznOMqZ9f3VUek8yN3VvSGdhRFU

**Comment by marcurdy** [comment]
Sorry.  I come from the Linux world of pip installs just working.  Cheers.

**Comment by Beercow** [comment]
NP. Glad to be of help.
