### ISSUE TITLE
No module named conf.config

### ISSUE THREAD

**Issue by markmorgan47** [mkorman90/VolatilityBot#2]
i keep getting this error:

C:\VolatilityBot>python db_builder.py
Traceback (most recent call last):
  File "db_builder.py", line 5, in <module>
    from conf.config import DB_ENGINE
ImportError: No module named conf.config

I have also tried with c:\python db_builder.py install

The conf.config folder is in the volatilitybot main folder along with the config file.

**Comment by mkorman90** [comment]
Hi, sorry for the late response. Which python version are you using?

**Comment by wlfrag** [comment]
i am using 2.7 and get this error

**Comment by luisco** [comment]
Create a empty file __init__.py in VolatilityBot/conf/

Works for me!
